export const prompts: Record<string, string[]> = {
  default: [
    "What was the highlight of your day?",
    "What emotions did you feel today and why?",
    "What was one challenge you faced today?",
    "What did you do for yourself today?",
    "What’s something you learned today?",
    "What would you do differently if you had a do-over?",
    "What moment brought you joy today?",
    "How do you feel about how today went?",
    "What drained your energy today?",
    "What gave you energy today?",
    "What surprised you today?",
    "Who or what made you smile today?",
    "Was there a moment where you felt at peace?",
    "How productive did you feel today?",
    "Did you do something creative or new today?",
    "What was the most emotional moment of your day?",
    "What did you avoid doing today, and why?",
    "How did you take care of your body today?",
    "What did you say no to that you’re proud of?",
    "Did you have any meaningful conversations today?",
    "What thoughts have been recurring today?",
    "What helped you feel grounded today?",
    "What would make tomorrow better?",
    "What kind of support do you wish you had today?",
    "If today was a color, what would it be and why?",
    "What are three things you're grateful for today?",
    "Describe a person who made your life easier recently.",
    "What's a simple pleasure you enjoyed today?",
    "What part of your routine are you thankful for?",
    "Write about a time you felt deeply supported.",
    "What’s a past challenge you now feel grateful for?",
    "List things in nature you’re grateful for right now.",
    "What part of your body or health are you grateful for?",
    "What recent memory makes you smile?",
    "What is something you're looking forward to?",
    "Who is someone in your life you haven’t thanked enough?",
    "What technology are you grateful for today?",
    "What’s a mistake that taught you something valuable?",
    "What are you grateful for about your home?",
    "What freedom are you thankful to have?",
    "What food did you enjoy today?",
    "Describe a moment of unexpected kindness.",
    "What skill or talent are you thankful you have?",
    "What makes your life easier that you often overlook?",
    "How does gratitude change your mood?",
    "What opportunity are you grateful for?",
    "Write a thank you note to someone, even if you don’t send it.",
    "What are you grateful for about your younger self?",
    "What relationships are you most thankful for today?",
    "What is something you’re grateful for that money can’t buy?",
    "What triggered a strong emotional response today?",
    "Describe the situation and your immediate reaction.",
    "How did your body feel during the trigger?",
    "What thoughts did you have during the experience?",
    "Did this moment remind you of something from the past?",
    "What unmet need might have caused the reaction?",
    "What would compassion toward yourself look like here?",
    "What could you try doing differently next time?",
    "What helped you calm down afterward?",
    "What patterns are you noticing around your triggers?",
    "Who was involved and how did they affect your emotions?",
    "Was your response aligned with how you want to act?",
    "How long did it take you to return to baseline?",
    "What internal beliefs might have influenced your reaction?",
    "Did you feel understood in that moment?",
    "What assumptions did you make that added fuel?",
    "What might the other person have been feeling?",
    "Have you experienced this kind of trigger before?",
    "What does your ideal response to this look like?",
    "What would it look like to let this go?",
    "How would you comfort a friend going through this?",
    "Are you holding on to anything from this experience?",
    "What’s underneath the emotion — fear, shame, guilt, anger?",
    "What part of yourself do you want to protect in these moments?",
    "How did this moment shape the rest of your day?",
    "Start by writing whatever comes to mind. Don’t censor.",
    "What are you thinking about right now?",
    "What emotion feels strongest in you today?",
    "Write a letter to someone you’ll never send.",
    "Describe your current mental state in detail.",
    "What do you wish you could say out loud?",
    "What’s the story behind a scar you have?",
    "How does your environment affect how you feel?",
    "What do you want most right now?",
    "Write about a memory you keep returning to.",
    "What are you running from, consciously or unconsciously?",
    "What would your ideal day look like?",
    "What does your inner critic sound like?",
    "What’s something you’ve never admitted to anyone?",
    "What lies have you told recently, even small ones?",
    "What would you do if you had no fear?",
    "If your thoughts were a landscape, what would they look like?",
    "What role does silence play in your life?",
    "What’s the difference between who you are and who you show others?",
    "What makes you feel most alive?",
    "What rules do you follow that no longer serve you?",
    "If you could ask the universe one question, what would it be?",
    "What do you miss about being a child?",
    "Describe your relationship with control.",
    "What would freedom mean to you right now?"
  ]
};
